[2022-12-14T12:07:31.218+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: weekly_wrapped_dag.generate_wrapped manual__2022-12-14T12:07:24.900137+00:00 [queued]>
[2022-12-14T12:07:31.238+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: weekly_wrapped_dag.generate_wrapped manual__2022-12-14T12:07:24.900137+00:00 [queued]>
[2022-12-14T12:07:31.240+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-14T12:07:31.242+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-14T12:07:31.243+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-14T12:07:31.258+0000] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): generate_wrapped> on 2022-12-14 12:07:24.900137+00:00
[2022-12-14T12:07:31.276+0000] {standard_task_runner.py:55} INFO - Started process 26297 to run task
[2022-12-14T12:07:31.286+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weekly_wrapped_dag', 'generate_wrapped', 'manual__2022-12-14T12:07:24.900137+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/weekly_dag.py', '--cfg-path', '/tmp/tmpb1z96mpr']
[2022-12-14T12:07:31.288+0000] {standard_task_runner.py:83} INFO - Job 70: Subtask generate_wrapped
[2022-12-14T12:07:31.401+0000] {task_command.py:389} INFO - Running <TaskInstance: weekly_wrapped_dag.generate_wrapped manual__2022-12-14T12:07:24.900137+00:00 [running]> on host b92abc15fbab
[2022-12-14T12:07:31.483+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weekly_wrapped_dag
AIRFLOW_CTX_TASK_ID=generate_wrapped
AIRFLOW_CTX_EXECUTION_DATE=2022-12-14T12:07:24.900137+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-14T12:07:24.900137+00:00
[2022-12-14T12:07:31.515+0000] {base.py:73} INFO - Using connection ID 'spotify_etl' for task execution.
[2022-12-14T12:07:31.526+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/weekly_dag.py", line 36, in generate_wrapped
    with open('sql/top_artist.sql', 'r') as s:
FileNotFoundError: [Errno 2] No such file or directory: 'sql/top_artist.sql'
[2022-12-14T12:07:31.542+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=weekly_wrapped_dag, task_id=generate_wrapped, execution_date=20221214T120724, start_date=20221214T120731, end_date=20221214T120731
[2022-12-14T12:07:31.566+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 70 for task generate_wrapped ([Errno 2] No such file or directory: 'sql/top_artist.sql'; 26297)
[2022-12-14T12:07:31.619+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-14T12:07:31.640+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
