[2022-12-16T01:54:48.294+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: daily_spotify_dag.transform_task manual__2022-12-16T01:54:37+00:00 [queued]>
[2022-12-16T01:54:48.302+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: daily_spotify_dag.transform_task manual__2022-12-16T01:54:37+00:00 [queued]>
[2022-12-16T01:54:48.302+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-16T01:54:48.303+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-16T01:54:48.304+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-16T01:54:48.313+0000] {taskinstance.py:1304} INFO - Executing <Task(PythonOperator): transform_task> on 2022-12-16 01:54:37+00:00
[2022-12-16T01:54:48.320+0000] {standard_task_runner.py:55} INFO - Started process 646 to run task
[2022-12-16T01:54:48.323+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'daily_spotify_dag', 'transform_task', 'manual__2022-12-16T01:54:37+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/daily_dag.py', '--cfg-path', '/tmp/tmpu0nk1p8f']
[2022-12-16T01:54:48.325+0000] {standard_task_runner.py:83} INFO - Job 20: Subtask transform_task
[2022-12-16T01:54:48.370+0000] {task_command.py:389} INFO - Running <TaskInstance: daily_spotify_dag.transform_task manual__2022-12-16T01:54:37+00:00 [running]> on host 158c8f40aaa8
[2022-12-16T01:54:48.409+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=daily_spotify_dag
AIRFLOW_CTX_TASK_ID=transform_task
AIRFLOW_CTX_EXECUTION_DATE=2022-12-16T01:54:37+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-16T01:54:37+00:00
[2022-12-16T01:54:48.418+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils/songs.py", line 76, in transform_data
    for item in data:
TypeError: 'NoneType' object is not iterable
[2022-12-16T01:54:48.426+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=daily_spotify_dag, task_id=transform_task, execution_date=20221216T015437, start_date=20221216T015448, end_date=20221216T015448
[2022-12-16T01:54:48.436+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 20 for task transform_task ('NoneType' object is not iterable; 646)
[2022-12-16T01:54:48.455+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-16T01:54:48.473+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
