[2022-12-14T08:47:54.026+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: daily_spotify_etl.refresh_access_token manual__2022-12-14T08:47:49.191173+00:00 [queued]>
[2022-12-14T08:47:54.033+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: daily_spotify_etl.refresh_access_token manual__2022-12-14T08:47:49.191173+00:00 [queued]>
[2022-12-14T08:47:54.036+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-14T08:47:54.038+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-14T08:47:54.039+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-14T08:47:54.052+0000] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): refresh_access_token> on 2022-12-14 08:47:49.191173+00:00
[2022-12-14T08:47:54.059+0000] {standard_task_runner.py:55} INFO - Started process 12432 to run task
[2022-12-14T08:47:54.063+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'daily_spotify_etl', 'refresh_access_token', 'manual__2022-12-14T08:47:49.191173+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/daily_dag.py', '--cfg-path', '/tmp/tmp358a_ev6']
[2022-12-14T08:47:54.065+0000] {standard_task_runner.py:83} INFO - Job 12: Subtask refresh_access_token
[2022-12-14T08:47:54.116+0000] {task_command.py:389} INFO - Running <TaskInstance: daily_spotify_etl.refresh_access_token manual__2022-12-14T08:47:49.191173+00:00 [running]> on host b92abc15fbab
[2022-12-14T08:47:54.155+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=daily_spotify_etl
AIRFLOW_CTX_TASK_ID=refresh_access_token
AIRFLOW_CTX_EXECUTION_DATE=2022-12-14T08:47:49.191173+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-14T08:47:49.191173+00:00
[2022-12-14T08:47:54.157+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/daily_dag.py", line 31, in refresh_access_token
    url=url,
NameError: name 'url' is not defined
[2022-12-14T08:47:54.172+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=daily_spotify_etl, task_id=refresh_access_token, execution_date=20221214T084749, start_date=20221214T084754, end_date=20221214T084754
[2022-12-14T08:47:54.182+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 12 for task refresh_access_token (name 'url' is not defined; 12432)
[2022-12-14T08:47:54.196+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-14T08:47:54.211+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
