[2022-12-14T12:18:17.866+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: weekly_wrapped_dag.generate_wrapped manual__2022-12-14T12:18:12.773982+00:00 [queued]>
[2022-12-14T12:18:17.872+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: weekly_wrapped_dag.generate_wrapped manual__2022-12-14T12:18:12.773982+00:00 [queued]>
[2022-12-14T12:18:17.873+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2022-12-14T12:18:17.873+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2022-12-14T12:18:17.874+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2022-12-14T12:18:17.881+0000] {taskinstance.py:1304} INFO - Executing <Task(_PythonDecoratedOperator): generate_wrapped> on 2022-12-14 12:18:12.773982+00:00
[2022-12-14T12:18:17.886+0000] {standard_task_runner.py:55} INFO - Started process 27058 to run task
[2022-12-14T12:18:17.889+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'weekly_wrapped_dag', 'generate_wrapped', 'manual__2022-12-14T12:18:12.773982+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/weekly_dag.py', '--cfg-path', '/tmp/tmpk1jw6p1y']
[2022-12-14T12:18:17.890+0000] {standard_task_runner.py:83} INFO - Job 72: Subtask generate_wrapped
[2022-12-14T12:18:17.939+0000] {task_command.py:389} INFO - Running <TaskInstance: weekly_wrapped_dag.generate_wrapped manual__2022-12-14T12:18:12.773982+00:00 [running]> on host b92abc15fbab
[2022-12-14T12:18:17.986+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=weekly_wrapped_dag
AIRFLOW_CTX_TASK_ID=generate_wrapped
AIRFLOW_CTX_EXECUTION_DATE=2022-12-14T12:18:12.773982+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-14T12:18:12.773982+00:00
[2022-12-14T12:18:17.992+0000] {base.py:73} INFO - Using connection ID 'spotify_etl' for task execution.
[2022-12-14T12:18:18.014+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/weekly_dag.py", line 37, in generate_wrapped
    with open('top_artist.sql', 'r') as s:
FileNotFoundError: [Errno 2] No such file or directory: 'top_artist.sql'
[2022-12-14T12:18:18.027+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=weekly_wrapped_dag, task_id=generate_wrapped, execution_date=20221214T121812, start_date=20221214T121817, end_date=20221214T121818
[2022-12-14T12:18:18.047+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 72 for task generate_wrapped ([Errno 2] No such file or directory: 'top_artist.sql'; 27058)
[2022-12-14T12:18:18.061+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-14T12:18:18.078+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
